
export const HEADER_KEY = {
  notShowHeader:"NotShowHeader",
  showNetworkHeader:"showNetworkHeader"
}
export const SCREENS = {
  Home: 'Home',
  TransactionDetail: 'Transactions.Detail',
  RegisterMain: 'RegisterMain',
  RegisterVerifyMnemonicMain: 'RegisterVerifyMnemonicMain',
  RegisterEnd: 'Register.End',
  RegisterRecoverMnemonicMain: 'RegisterRecoverMnemonicMain',
  RegisterNewLedgerMain: 'RegisterNewLedgerMain',
  Tokens: 'Tokens',
  Nfts: 'Nfts',
  TokenDetail: 'Tokens.Detail',
  NftsDetail: 'Nfts.Detail',
  TransferTokensScreen: 'TransferTokensScreen',
  RegisterIntro: 'Register.Intro',
  RegisterNewUser: 'Register.NewUser',
  RegisterNotNewUser: 'Register.NotNewUser',
  RegisterNewMnemonic: 'Register.NewMnemonic',
  RegisterVerifyMnemonic: 'Register.VerifyMnemonic',
  RegisterRecoverMnemonic: 'Register.RecoverMnemonic',
  RegisterNewLedger:'Register.NewLedger',
  Send:'Send',
  TransferNFT:'TransferNFT',
  Transactions:'Transactions',
  Dashboard:'Dashboard',
  Camera:'Camera',
  Governance:'Governance',
  GovernanceDetails:'Governance.Details',
  NetworkSelect:'Network.select',
  ValidatorDetails:'Validator.Details',
  ValidatorList:'Validator.List',
  TxPendingResult:'TxPendingResult',
  TxSuccessResult:'TxSuccessResult',
  TxFailedResult:'TxFailedResult',
  Setting:'Setting',
  SettingSelectAccount:'SettingSelectAccount',
  SettingViewPrivateData:'Setting.ViewPrivateData',
  SettingVersion:'Setting.Version',
  AddressBook:'AddressBook',
  AddAddressBook:'AddAddressBook',
  Browser:"Browser",
  BookMarks:'BookMarks',
  WebIntro:'Web.Intro',
  WebDApp:'Web.dApp',
  Invest:'Invest',
  Delegate:'Delegate',
  DelegateDetail:'Delegate.Detail',
  Redelegate:'Redelegate',
  Undelegate:'Undelegate',
  TABS:{
    Main:'Main',
    Home:'Home',
    Browser:'Browser',
    Invest:'Invest',
    Settings:'Settings',
    SendNavigation:'SendNavigation'
  },
  STACK:{
    Unlock:'Unlock',
    MainTab:'MainTab',
    Register:'Register',
    Others:'Others',
    AddressBooks:'AddressBooks'
  }
};

export const SCREENS_TITLE = {
  [SCREENS.TABS.Home]: HEADER_KEY.showNetworkHeader,
  [SCREENS.TABS.Main]: 'Main',
  [SCREENS.TABS.Browser]: 'Browser',
  [SCREENS.TABS.Settings]: 'Settings',
  [SCREENS.TABS.SendNavigation]: '',
  [SCREENS.Home]: HEADER_KEY.showNetworkHeader,
  [SCREENS.TransactionDetail]: 'Transaction Detail',
  [SCREENS.RegisterMain]: HEADER_KEY.notShowHeader,
  [SCREENS.RegisterVerifyMnemonicMain]: HEADER_KEY.notShowHeader,
  [SCREENS.RegisterEnd]: HEADER_KEY.notShowHeader,
  [SCREENS.RegisterRecoverMnemonicMain]: HEADER_KEY.notShowHeader,
  [SCREENS.RegisterNewLedgerMain]: HEADER_KEY.notShowHeader,
  [SCREENS.Tokens]: HEADER_KEY.showNetworkHeader,
  [SCREENS.Nfts]: HEADER_KEY.showNetworkHeader,
  [SCREENS.TokenDetail]: HEADER_KEY.showNetworkHeader,
  [SCREENS.NftsDetail]: HEADER_KEY.showNetworkHeader,
  [SCREENS.TransferTokensScreen]: HEADER_KEY.showNetworkHeader,
  [SCREENS.RegisterIntro]: HEADER_KEY.notShowHeader,
  [SCREENS.RegisterNewUser]: HEADER_KEY.notShowHeader,
  [SCREENS.RegisterNotNewUser]: HEADER_KEY.notShowHeader,
  [SCREENS.RegisterNewMnemonic]: HEADER_KEY.notShowHeader,
  [SCREENS.RegisterVerifyMnemonic]: HEADER_KEY.notShowHeader,
  [SCREENS.RegisterRecoverMnemonic]: HEADER_KEY.notShowHeader,
  [SCREENS.RegisterNewLedger]: HEADER_KEY.notShowHeader,
  [SCREENS.Send]: HEADER_KEY.showNetworkHeader,
  [SCREENS.TransferNFT]: HEADER_KEY.showNetworkHeader,
  [SCREENS.Transactions]: 'Transaction history',
  [SCREENS.Camera]: HEADER_KEY.notShowHeader,
  [SCREENS.Governance]: HEADER_KEY.showNetworkHeader,
  [SCREENS.GovernanceDetails]: HEADER_KEY.showNetworkHeader,
  [SCREENS.Dashboard]: HEADER_KEY.showNetworkHeader,
  [SCREENS.NetworkSelect]: HEADER_KEY.showNetworkHeader,
  [SCREENS.ValidatorDetails]: HEADER_KEY.showNetworkHeader,
  [SCREENS.ValidatorList]: HEADER_KEY.showNetworkHeader,
  [SCREENS.TxPendingResult]: HEADER_KEY.notShowHeader,
  [SCREENS.TxSuccessResult]: HEADER_KEY.notShowHeader,
  [SCREENS.TxFailedResult]: HEADER_KEY.notShowHeader,
  [SCREENS.Setting]: HEADER_KEY.notShowHeader,
  [SCREENS.SettingSelectAccount]: 'Select Account',
  [SCREENS.SettingViewPrivateData]: HEADER_KEY.showNetworkHeader,
  [SCREENS.SettingVersion]: 'About',
  [SCREENS.AddressBook]: HEADER_KEY.showNetworkHeader,
  [SCREENS.AddAddressBook]: 'Add new contact',
  [SCREENS.Browser]: 'Browser',
  [SCREENS.BookMarks]: 'Bookmarks',
  [SCREENS.WebIntro]: '',
  [SCREENS.WebDApp]: '',
  [SCREENS.Invest]: HEADER_KEY.showNetworkHeader,
  [SCREENS.Delegate]: HEADER_KEY.showNetworkHeader,
  [SCREENS.DelegateDetail]: HEADER_KEY.showNetworkHeader,
  [SCREENS.Redelegate]: HEADER_KEY.showNetworkHeader,
  [SCREENS.Undelegate]: HEADER_KEY.showNetworkHeader,
  [SCREENS.STACK.Unlock]: '',
  [SCREENS.STACK.MainTab]: '',
  [SCREENS.STACK.Register]: '',
  [SCREENS.STACK.Others]: '',
  [SCREENS.STACK.AddressBooks]: '',
};
