export const SCREENS = {
  Home: 'Home',
  TransactionDetail: 'Transactions.Detail',
  RegisterMain: 'RegisterMain',
  RegisterVerifyMnemonicMain: 'RegisterVerifyMnemonicMain',
  RegisterEnd: 'RegisterEnd',
  RegisterRecoverMnemonicMain: 'RegisterRecoverMnemonicMain',
  RegisterNewLedgerMain: 'RegisterNewLedgerMain',
  Tokens: 'Tokens',
  Nfts: 'Nfts',
  TokenDetail: 'Tokens.Detail',
  NftsDetail: 'Nfts.Detail',
  TransferTokensScreen: 'TransferTokensScreen',
  RegisterIntro: 'Register.Intro',
  RegisterNewUser: 'Register.NewUser',
  RegisterNotNewUser: 'Register.NotNewUser',
  RegisterNewMnemonic: 'Register.NewMnemonic',
  RegisterVerifyMnemonic: 'Register.VerifyMnemonic',
  RegisterRecoverMnemonic: 'Register.RecoverMnemonic',
  RegisterNewLedger:'Register.NewLedger',
  Send:'Send',
  TransferNFT:'TransferNFT',
  Transactions:'Transactions',
  Dashboard:'Dashboard',
  Camera:'Camera',
  Governance:'Governance',
  GovernanceDetails:'Governance.Details',
  NetworkSelect:'Network.select',
  ValidatorDetails:'Validator.Details',
  ValidatorList:'Validator.List',
  TxPendingResult:'TxPendingResult',
  TxSuccessResult:'TxSuccessResult',
  TxFailedResult:'TxFailedResult',
  Setting:'Setting',
  SettingSelectAccount:'SettingSelectAccount',
  SettingViewPrivateData:'Setting.ViewPrivateData',
  SettingVersion:'Setting.Version',
  AddressBook:'AddressBook',
  AddAddressBook:'AddAddressBook',
  Browser:"Browser",
  BookMarks:'BookMarks',
  WebIntro:'Web.Intro',
  WebDApp:'Web.dApp',
  Invest:'Invest',
  Delegate:'Delegate',
  DelegateDetail:'Delegate.Detail',
  Redelegate:'Redelegate',
  Undelegate:'Undelegate',
  TABS:{
    Main:'Main',
    Home:'Home',
    Browser:'Browser',
    Invest:'Invest',
    Settings:'Settings',
    SendNavigation:'SendNavigation'
  },
  STACK:{
    Unlock:'Unlock',
    MainTab:'MainTab',
    Register:'Register',
    Others:'Others',
    AddressBooks:'AddressBooks'
  }
};

export const SCREENS_TITLE = {
  [SCREENS.TABS.Home]: '',
  [SCREENS.TABS.Main]: 'Main',
  [SCREENS.TABS.Browser]: 'Browser',
  [SCREENS.TABS.Settings]: 'Settings',
  [SCREENS.TABS.SendNavigation]: '',
  [SCREENS.Home]: '',
  [SCREENS.TransactionDetail]: 'Transaction Detail',
  [SCREENS.RegisterMain]: '',
  [SCREENS.RegisterVerifyMnemonicMain]: '',
  [SCREENS.RegisterEnd]: '',
  [SCREENS.RegisterRecoverMnemonicMain]: '',
  [SCREENS.RegisterNewLedgerMain]: '',
  [SCREENS.Tokens]: '',
  [SCREENS.Nfts]: '',
  [SCREENS.TokenDetail]: '',
  [SCREENS.NftsDetail]: '',
  [SCREENS.TransferTokensScreen]: '',
  [SCREENS.RegisterIntro]: '',
  [SCREENS.RegisterNewUser]: '',
  [SCREENS.RegisterNotNewUser]: '',
  [SCREENS.RegisterNewMnemonic]: '',
  [SCREENS.RegisterVerifyMnemonic]: '',
  [SCREENS.RegisterRecoverMnemonic]: '',
  [SCREENS.RegisterNewLedger]: '',
  [SCREENS.Send]: '',
  [SCREENS.TransferNFT]: '',
  [SCREENS.Transactions]: '',
  [SCREENS.Camera]: '',
  [SCREENS.Governance]: 'Governance',
  [SCREENS.GovernanceDetails]: 'Proposal',
  [SCREENS.Dashboard]: 'Dashboard',
  [SCREENS.NetworkSelect]: '',
  [SCREENS.ValidatorDetails]: 'Validator Details',
  [SCREENS.ValidatorList]: 'All Active Validators',
  [SCREENS.TxPendingResult]: '',
  [SCREENS.TxSuccessResult]: '',
  [SCREENS.TxFailedResult]: '',
  [SCREENS.Setting]: 'Settings',
  [SCREENS.SettingSelectAccount]: 'Select Account',
  [SCREENS.SettingViewPrivateData]: '',
  [SCREENS.SettingVersion]: 'Version',
  [SCREENS.AddressBook]: 'Address Book',
  [SCREENS.AddAddressBook]: '',
  [SCREENS.Browser]: '',
  [SCREENS.BookMarks]: 'Bookmarks',
  [SCREENS.WebIntro]: '',
  [SCREENS.WebDApp]: '',
  [SCREENS.Invest]: '',
  [SCREENS.Delegate]: 'Stake',
  [SCREENS.DelegateDetail]: 'Delegate Detail',
  [SCREENS.Redelegate]: 'Switch Validator',
  [SCREENS.Undelegate]: 'Unstake',
  [SCREENS.STACK.Unlock]: '',
  [SCREENS.STACK.MainTab]: '',
  [SCREENS.STACK.Register]: '',
  [SCREENS.STACK.Others]: '',
  [SCREENS.STACK.AddressBooks]: '',
};
