import images from "@src/assets/images";

export const HEADER_KEY = {
  notShowHeader: 'NOT_SHOW_HEADER',
  showNetworkHeader: 'SHOW_NETWORK_HEADER'
};
export const defaultAll = { label: 'All', value: 'All', image: images.crypto };
export const SCREENS = {
  Home: 'Home',
  TransactionDetail: 'Transactions.Detail',
  RegisterMain: 'RegisterMain',
  RegisterVerifyMnemonicMain: 'RegisterVerifyMnemonicMain',
  RegisterEnd: 'Register.End',
  RegisterRecoverMnemonicMain: 'RegisterRecoverMnemonicMain',
  RegisterNewLedgerMain: 'RegisterNewLedgerMain',
  Tokens: 'Tokens',
  Nfts: 'Nfts',
  TokenDetail: 'Tokens.Detail',
  NftsDetail: 'Nfts.Detail',
  TransferTokensScreen: 'TransferTokensScreen',
  RegisterIntro: 'Register.Intro',
  RegisterNewUser: 'Register.NewUser',
  RegisterNotNewUser: 'Register.NotNewUser',
  RegisterNewMnemonic: 'Register.NewMnemonic',
  RegisterVerifyMnemonic: 'Register.VerifyMnemonic',
  RegisterRecoverMnemonic: 'Register.RecoverMnemonic',
  RegisterNewLedger: 'Register.NewLedger',
  Send: 'Send',
  TransferNFT: 'TransferNFT',
  Transactions: 'Transactions',
  Dashboard: 'Dashboard',
  Camera: 'Camera',
  Governance: 'Governance',
  GovernanceDetails: 'Governance.Details',
  NetworkSelect: 'Network.select',
  ValidatorDetails: 'Validator.Details',
  ValidatorList: 'Validator.List',
  TxPendingResult: 'TxPendingResult',
  TxSuccessResult: 'TxSuccessResult',
  TxFailedResult: 'TxFailedResult',
  Setting: 'Setting',
  SettingSelectAccount: 'SettingSelectAccount',
  SettingViewPrivateData: 'Setting.ViewPrivateData',
  SettingVersion: 'Setting.Version',
  AddressBook: 'AddressBook',
  AddAddressBook: 'AddAddressBook',
  Browser: 'Browser',
  BookMarks: 'BookMarks',
  WebIntro: 'Web.Intro',
  WebDApp: 'Web.dApp',
  Invest: 'Invest',
  Delegate: 'Delegate',
  SendTron: 'SendTron',
  Notifications: 'Notifications',
  DelegateDetail: 'Delegate.Detail',
  Redelegate: 'Redelegate',
  Undelegate: 'Undelegate',
  TABS: {
    Main: 'Main',
    Home: 'Home',
    Browser: 'Browser',
    Invest: 'Invest_Tab',
    Settings: 'Settings',
    SendNavigation: 'SendNavigation'
  },
  STACK: {
    Unlock: 'Unlock',
    MainTab: 'MainTab',
    Register: 'Register',
    Others: 'Others',
    AddressBooks: 'AddressBooks',
  }
};
export const ICONS_TITLE = {
  [SCREENS.TABS.Invest]: 'invest',
  [SCREENS.TABS.Main]: 'home',
  [SCREENS.TABS.Browser]: 'browser',
  [SCREENS.TABS.Settings]: 'setting',
  [SCREENS.TABS.SendNavigation]: ''
};
export const SCREENS_TITLE = {
  [SCREENS.TABS.Invest]: 'Invest',
  [SCREENS.TABS.Main]: 'Home',
  [SCREENS.TABS.Browser]: 'Browser',
  [SCREENS.TABS.Settings]: 'Settings',
  [SCREENS.TABS.SendNavigation]: '',
  [SCREENS.Home]: HEADER_KEY.showNetworkHeader,
  [SCREENS.TransactionDetail]: 'Transaction Detail',
  [SCREENS.RegisterMain]: HEADER_KEY.notShowHeader,
  [SCREENS.RegisterVerifyMnemonicMain]: HEADER_KEY.notShowHeader,
  [SCREENS.RegisterEnd]: HEADER_KEY.notShowHeader,
  [SCREENS.RegisterRecoverMnemonicMain]: HEADER_KEY.notShowHeader,
  [SCREENS.RegisterNewLedgerMain]: HEADER_KEY.notShowHeader,
  [SCREENS.Tokens]: HEADER_KEY.showNetworkHeader,
  [SCREENS.Nfts]: HEADER_KEY.showNetworkHeader,
  [SCREENS.TokenDetail]: HEADER_KEY.showNetworkHeader,
  [SCREENS.NftsDetail]: HEADER_KEY.showNetworkHeader,
  [SCREENS.TransferTokensScreen]: HEADER_KEY.showNetworkHeader,
  [SCREENS.RegisterIntro]: HEADER_KEY.notShowHeader,
  [SCREENS.RegisterNewUser]: HEADER_KEY.notShowHeader,
  [SCREENS.RegisterNotNewUser]: HEADER_KEY.notShowHeader,
  [SCREENS.RegisterNewMnemonic]: HEADER_KEY.notShowHeader,
  [SCREENS.RegisterVerifyMnemonic]: HEADER_KEY.notShowHeader,
  [SCREENS.RegisterRecoverMnemonic]: HEADER_KEY.notShowHeader,
  [SCREENS.RegisterNewLedger]: HEADER_KEY.notShowHeader,
  [SCREENS.Send]: HEADER_KEY.showNetworkHeader,
  [SCREENS.TransferNFT]: HEADER_KEY.showNetworkHeader,
  [SCREENS.Transactions]: 'Transaction History',
  [SCREENS.Camera]: HEADER_KEY.notShowHeader,
  [SCREENS.Governance]: HEADER_KEY.showNetworkHeader,
  [SCREENS.GovernanceDetails]: HEADER_KEY.showNetworkHeader,
  [SCREENS.Dashboard]: HEADER_KEY.showNetworkHeader,
  [SCREENS.SendTron]: HEADER_KEY.showNetworkHeader,
  [SCREENS.Notifications]: HEADER_KEY.showNetworkHeader,
  [SCREENS.NetworkSelect]: HEADER_KEY.showNetworkHeader,
  [SCREENS.ValidatorDetails]: HEADER_KEY.showNetworkHeader,
  [SCREENS.ValidatorList]: HEADER_KEY.showNetworkHeader,
  [SCREENS.TxPendingResult]: HEADER_KEY.notShowHeader,
  [SCREENS.TxSuccessResult]: HEADER_KEY.notShowHeader,
  [SCREENS.TxFailedResult]: HEADER_KEY.notShowHeader,
  [SCREENS.Setting]: HEADER_KEY.notShowHeader,
  [SCREENS.SettingSelectAccount]: 'Select Account',
  [SCREENS.SettingViewPrivateData]: 'Mnemonic Seed',
  [SCREENS.SettingVersion]: 'About',
  [SCREENS.AddressBook]: HEADER_KEY.showNetworkHeader,
  [SCREENS.AddAddressBook]: 'Add new contract',
  [SCREENS.Browser]: 'Browser',
  [SCREENS.BookMarks]: 'Bookmarks',
  [SCREENS.WebIntro]: '',
  [SCREENS.WebDApp]: '',
  [SCREENS.Invest]: HEADER_KEY.showNetworkHeader,
  [SCREENS.Delegate]: HEADER_KEY.showNetworkHeader,
  [SCREENS.DelegateDetail]: HEADER_KEY.showNetworkHeader,
  [SCREENS.Redelegate]: HEADER_KEY.showNetworkHeader,
  [SCREENS.Undelegate]: HEADER_KEY.showNetworkHeader,
  [SCREENS.STACK.Unlock]: '',
  [SCREENS.STACK.MainTab]: '',
  [SCREENS.STACK.Register]: '',
  [SCREENS.STACK.Others]: '',
  [SCREENS.STACK.AddressBooks]: ''
};
export const TYPE_ACTIONS_COSMOS_HISTORY = {
  ['delegate']: 'delegate',
  ['send']: 'send',
  ['receive']: 'receive',
  ['withdraw_delegator_reward']: 'withdraw_delegator_reward',
  ['begin_redelegate']: 'begin_redelegate',
  ['begin_unbonding']: 'begin_unbonding',
  ['transfer']: 'transfer',
  ['execute']: 'execute',
  ['wasm/MsgExecuteContract']: '/cosmwasm.wasm.v1.MsgExecuteContract',
  ['bank/MsgSend']: '/cosmos.bank.v1beta1.MsgSend',
  ['distribution/MsgWithdrawDelegatorReward']:
    '/cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward',
  ['staking/MsgDelegate']: '/cosmos.staking.v1beta1.MsgDelegate',
  ['staking/MsgUndelegate']: '/cosmos.staking.v1beta1.MsgUndelegate',
  ['submit_proposal']: 'submit_proposal',
  ['gov/MsgSubmitProposal']: '/cosmos.gov.v1beta1.MsgSubmitProposal'
};
export const TITLE_TYPE_ACTIONS_COSMOS_HISTORY = {
  [TYPE_ACTIONS_COSMOS_HISTORY.receive]: 'Receive'
};