"use strict";
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.27.1
// source: cosmos_proto/cosmos.proto
Object.defineProperty(exports, "__esModule", { value: true });
exports.protobufPackage = void 0;
/* eslint-disable */
exports.protobufPackage = "cosmos_proto";
//# sourceMappingURL=cosmos.js.map