const images = {
    launch: require('./Launch.png'),
   launch_dark: require('./Launch_dark.png'),
   noti: require('./Noti.png'),
   noti_dark: require('./Noti_dark.png'),
   carbon_notification: require('./carbon_notification.png'),
   carbon_notification_dark: require('./carbon_notification_dark.png'),
   empty: require('./empty.png'),
   empty_dark: require('./empty_dark.png'),
   eye: require('./eye.png'),
   fail: require('./fail.png'),
   fail_dark: require('./fail_dark.png'),
   line_dark_pending_long: require('./line-dark-pending-long.png'),
   line_fail_long_dark: require('./line_fail_long_dark.png'),
   line_fail_short: require('./line_fail_short.png'),
   line_fail_short_dark: require('./line_fail_short_dark.png'),
   line_faild_long: require('./line_faild_long.png'),
   line_pending_long: require('./line_pending_long.png'),
   line_pending_short: require('./line_pending_short.png'),
   line_pending_short_dark: require('./line_pending_short_dark.png'),
   line_success_long: require('./line_success_long.png'),
   line_success_short: require('./line_success_short.png'),
   line_success_short_dark: require('./line_success_short_dark.png'),
   line_sucess_long_dark: require('./line_sucess_long_dark.png'),
   pending_dark: require('./pending-dark.png'),
   pending: require('./pending.png'),
   process_pending: require('./process_pending.png'),
   success: require('./success.png'),
   success_dark: require('./success_dark.png'),
};
export default images;
