const currencies = {
  ars: {
    name: "Argentine Peso",
    unit: "ARS",
    symbol: "$",
    id: "argentine-peso",
  },
  aud: {
    name: "Australian Dollar",
    unit: "AUD",
    symbol: "A$",
    id: "australian-dollar",
  },
  bdt: {
    name: "Bangladeshi Taka",
    unit: "BDT",
    symbol: "৳",
    id: "bangladeshi-taka",
  },
  bhd: {
    name: "Bahraini Dinar",
    unit: "BHD",
    symbol: ".د.ب",
    id: "bahraini-dinar",
  },
  bmd: {
    name: "Bermudian Dollar",
    unit: "BMD",
    symbol: "$",
    id: "bermudan-dollar",
  },
  brl: { name: "Brazil Real", unit: "BRL", symbol: "R$", id: "brazilian-real" },
  gbp: {
    name: "British Pound Sterling",
    unit: "GBP",
    symbol: "£",
    id: "british-pound-sterling",
  },
  mmk: { name: "Burmese Kyat", unit: "MMK", symbol: "K", id: "myanma-kyat" },
  cad: {
    name: "Canadian Dollar",
    unit: "CAD",
    symbol: "$",
    id: "canadian-dollar",
  },
  clp: { name: "Chilean Peso", unit: "CLP", symbol: "$", id: "chilean-peso" },
  cny: {
    name: "Chinese Yuan",
    unit: "CNY",
    symbol: "¥",
    id: "chinese-yuan-renminbi",
  },
  czk: {
    name: "Czech Koruna",
    unit: "CZK",
    symbol: "Kč",
    id: "czech-republic-koruna",
  },
  dkk: { name: "Danish Krone", unit: "DKK", symbol: "kr", id: "danish-krone" },
  eur: { name: "Euro", unit: "EUR", symbol: "€", id: "euro" },
  hkd: {
    name: "Hong Kong Dollar",
    unit: "HKD",
    symbol: "$",
    id: "hong-kong-dollar",
  },
  huf: {
    name: "Hungarian Forint",
    unit: "HUF",
    symbol: "Ft",
    id: "hungarian-forint",
  },
  inr: { name: "Indian Rupee", unit: "INR", symbol: "₹", id: "indian-rupee" },
  idr: {
    name: "Indonesian Rupiah",
    unit: "IDR",
    symbol: "Rp",
    id: "indonesian-rupiah",
  },
  ils: {
    name: "Israeli New Shekel",
    unit: "ILS",
    symbol: "₪",
    id: "israeli-new-sheqel",
  },
  jpy: { name: "Japanese Yen", unit: "JPY", symbol: "¥", id: "japanese-yen" },
  kwd: {
    name: "Kuwaiti Dinar",
    unit: "KWD",
    symbol: "د.ك",
    id: "kuwaiti-dinar",
  },
  lkr: {
    name: "Sri Lankan Rupee",
    unit: "LKR",
    symbol: "රු",
    id: "sri-lankan-rupee",
  },
  myr: {
    name: "Malaysian Ringgit",
    unit: "MYR",
    symbol: "RM",
    id: "malaysian-ringgit",
  },
  mxn: { name: "Mexican Peso", unit: "MXN", symbol: "$", id: "mexican-peso" },
  twd: {
    name: "New Taiwan Dollar",
    unit: "TWD",
    symbol: "$",
    id: "new-taiwan-dollar",
  },
  nzd: {
    name: "New Zealand Dollar",
    unit: "NZD",
    symbol: "$",
    id: "new-zealand-dollar",
  },
  nok: {
    name: "Norwegian Krone",
    unit: "NOK",
    symbol: "kr",
    id: "norwegian-krone",
  },
  pkr: {
    name: "Pakistan Rupee",
    unit: "PKR",
    symbol: "₨",
    id: "pakistani-rupee",
  },
  php: {
    name: "Philippine Peso",
    unit: "PHP",
    symbol: "₱",
    id: "philippine-peso",
  },
  pln: { name: "Polish Zloty", unit: "PLN", symbol: "zł", id: "polish-zloty" },
  rub: { name: "Russia Ruble", unit: "RUB", symbol: "₽", id: "russian-ruble" },
  sar: { name: "Saudi Riyal", unit: "SAR", symbol: "ر.س", id: "saudi-riyal" },
  sgd: {
    name: "Singapore Dollar",
    unit: "SGD",
    symbol: "$",
    id: "singapore-dollar",
  },
  zar: {
    name: "South Africa Rand",
    unit: "ZAR",
    symbol: "R",
    id: "south-african-rand",
  },
  krw: {
    name: "South Korean Won",
    unit: "KRW",
    symbol: "₩",
    id: "south-korean-won",
  },
  sek: {
    name: "Swedish Krona",
    unit: "SEK",
    symbol: "kr",
    id: "swedish-krona",
  },
  chf: { name: "Swiss Franc", unit: "CHF", symbol: "Fr", id: "swiss-franc" },
  thb: { name: "Thai Baht", unit: "THB", symbol: "฿", id: "thai-baht" },
  try: { name: "Turkey Lira", unit: "TRY", symbol: "₺", id: "turkish-lira" },
  aed: {
    name: "United Arab Emirates Dirham",
    unit: "AED",
    symbol: "د.إ",
    id: "united-arab-emirates-dirham",
  },
  usd: {
    name: "United States Dollar",
    unit: "USD",
    symbol: "$",
    id: "united-states-dollar",
  },
  vef: {
    name: "Venezuelan bolivar fuerte",
    unit: "VEF",
    symbol: "Bs",
    id: "venezuelan-bolívar-fuerte",
  },
  vnd: {
    name: "Vietnamese dong",
    unit: "VND",
    symbol: "₫",
    id: "vietnamese-dong",
  },
};

module.exports = { currencies };
